### ISSUE TITLE
Can't send USSD Codes

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-sms-tool-js#10]
Can't send the USSD Code, get "TypeError: res.stdout is undefined" error:

![image](https://github.com/4IceG/luci-app-sms-tool-js/assets/233979/e343e6b7-25dc-4f8d-b99b-c0e3bc0ca515)

Configuration:

![image](https://github.com/4IceG/luci-app-sms-tool-js/assets/233979/0684625c-ec8c-49fe-852d-1d1c57d3f9c3)

Without "Sending USSD code in plain text" tick, it doesn't even try to send the Code.

**Comment by 4IceG** [comment]
Sending USSD codes works. The error may be caused by the unavailability of the modem. Remember that the modem cannot have LTE set/forced.

**Comment by bam80** [comment]
I'll check it again, but AFAIK the modem is available and connected to LTE as usual.

**Comment by 4IceG** [comment]
USSD codes do not work on LTE, the modem must be set to AUTO. If possible, reset the modem to default settings and then check.

**Comment by bam80** [comment]
Do you know the AT command to check?
The thing is it seems worked earlier on the same system with Quectel modem.
I didn't change modem settings (AFAIK), but upgraded OpenWrt and packages.
I have another system with the same configuration but different carrier, and USSD work there.

**Comment by 4IceG** [comment]
Have you tried restarting the modem? Restore it to default settings?

I don't know what kind of modem it is, so I can't guess at commands, for Quectels these commands are known, and if not, they are easy to find.

**Comment by bam80** [comment]
Sorry I didn't put it clear - both system's are with Quectel modems.
I don't have the access right now, but wanted to prepare things to try later.

**Comment by bam80** [comment]
Can I try to send USSD via CLI somehow?

**Comment by 4IceG** [comment]
> Can I try to send USSD via CLI somehow?

I don't know anything about being able to send USSD codes this way.
