### ISSUE TITLE
Can't Save Config

### ISSUE THREAD

**Issue by rayhanbone** [4IceG/luci-app-sms-tool-js#12]
Cant save and apply because of error Led Name
In my case, no dropdown led name for use.
Iam using openwrt 23.05.2 for STB

**Comment by 4IceG** [comment]
Hi @rayhanbone , 
Check the new version of the package, I removed the LED selection from the configuration save.

**Comment by rayhanbone** [comment]
> Hi @rayhanbone , Check the new version of the package, I removed the LED selection from the configuration save.

Ok thanks, working now and pefect
