### ISSUE TITLE
cannot install the latest luci-app-sms-tool-js

### ISSUE THREAD

**Issue by pawol** [4IceG/luci-app-sms-tool-js#14]
cannot install the latest luci-app-sms-tool-js

root@MF286D:/tmp/myrepo# opkg install luci-app-sms-tool-js_2.0.20-20240121_all.i
pk
Upgrading luci-app-sms-tool-js on root from 2.0.18-20231008 to 2.0.20-20240121..                                                                                       .
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.137-1-b5ab1d                                                                                       6f6247c989eccb311be6c450fd) for kmod-nls-base
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nls-base found,                                                                                        but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.137-1-b5ab1d                                                                                       6f6247c989eccb311be6c450fd) for kmod-usb-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-core found,                                                                                        but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.137-1-b5ab1d                                                                                       6f6247c989eccb311be6c450fd) for kmod-usb-serial
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-serial foun                                                                                       d, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.137-1-b5ab1d                                                                                       6f6247c989eccb311be6c450fd) for kmod-usb-serial-wwan
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-serial-wwan                                                                                        found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.137-1-b5ab1d                                                                                       6f6247c989eccb311be6c450fd) for kmod-usb-serial-option
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-serial-opti                                                                                       on found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-                                                                                       app-sms-tool-js:
 *      kernel (= 5.15.137-1-b5ab1d6f6247c989eccb311be6c450fd)
 * opkg_install_cmd: Cannot install package luci-app-sms-tool-js.
root@MF286D:/tmp/myrepo#

**Comment by pawol** [comment]
root@MF286D:/tmp/myrepo# uname -a
Linux MF286D 5.15.137 #0 SMP Tue Nov 14 13:38:11 2023 armv7l GNU/Linux

**Comment by 4IceG** [comment]
OK Thanks, 
I'll fix it in the next repository update. If you don't use Chinese, the update can wait.
