### ISSUE TITLE
New Translation for Chinese Simplified.

### ISSUE THREAD

**Issue by murraychou** [4IceG/luci-app-sms-tool-js#18]
[luci-app-sms-tool-js.zip](https://github.com/4IceG/luci-app-sms-tool-js/files/15281621/luci-app-sms-tool-js.zip)
Hello, developer:
I've change this Chinese Simplified translation file. I think it is more comprehensive than before.

**Comment by 4IceG** [comment]
Hi @murraychou ,
Ok, thanks for the better translation. I will use your translation in new compilation.
