### ISSUE TITLE
ACL configuration files access

### ISSUE THREAD

**Issue by GektorUA** [4IceG/luci-app-sms-tool-js#2]
Seems that version works with ACL, but user with full rights can't write configuration, i am think it because configuration files stored in not usual directory and doesn't accessed for user. Can you check it?

**Comment by 4IceG** [comment]
I don't have a multi-user configuration, one user has no trouble saving the configuration. I added the conffiles section to the makefile and the new build should make it easier to access the configuration files.

The location of the files will not change (to comply with the UCI).
