### ISSUE TITLE
AT Commands: "Command to send" field is not populated

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-sms-tool-js#6]
If there is only one command configured, there is no way to fill the field by selecting a command from "User AT commands" drop-down list:
![image](https://github.com/4IceG/luci-app-sms-tool-js/assets/233979/12622bce-96e6-415a-93b6-bf8f2f74d8cb)

OpenWrt 23.05.0-rc2

**Comment by 4IceG** [comment]
There is one sample command so that the user can see how he/she should/can add additional commands.

You can't select this command anyway, it's not an error. The option works only when changing the command from the list.

**Comment by bam80** [comment]
But if you add a command you can select the original one.
Also alternative app from @koshev-msk work well in the same single-entry scenario
